"""add column runnersOn to plays table

Revision ID: 09b867b67369
Revises: 25fad35cf469
Create Date: 2023-04-23 16:57:37.392197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b867b67369'
down_revision = '25fad35cf469'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plays', sa.Column('runnersOn', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plays', schema=None) as batch_op:
        batch_op.drop_column('runnersOn')

    # ### end Alembic commands ###
