"""add column outs to plays table

Revision ID: 25fad35cf469
Revises: 530df8370aaf
Create Date: 2023-04-23 16:48:54.245781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fad35cf469'
down_revision = '530df8370aaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plays', sa.Column('outs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
