"""add column inning to the plays table

Revision ID: 530df8370aaf
Revises: 0eff83ac7c51
Create Date: 2023-04-23 16:43:55.283547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530df8370aaf'
down_revision = '0eff83ac7c51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plays', sa.Column('inning', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
