"""add column atBatId to plays table

Revision ID: 9cd25c0e778b
Revises: 0eff83ac7c51
Create Date: 2023-04-12 20:52:01.353968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd25c0e778b'
down_revision = '0eff83ac7c51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plays', sa.Column('atBatId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(sa.Column('plays', 'atBatId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
